### PR TITLE
Setup for React Development - JacobMGEvans

### PR DESCRIPTION
**Pull request by JacobMGEvans**
- Still, need to add eslintrc

### CODE REVIEW

**Comment by JacobMGEvans** [comment]
I wouldn't actually merge this into master unless you are willing to do a lot of the refactoring. I haven't integrated all of the stylings from the GIANT CSS file into the component for NAVBAR and also have not integrated the material icons and font awesome, I did add some dependencies that would be helpful for that, check package.json

**Comment by shan5742** [comment]
Hey man, thanks so much for doing this, I will have a look over it, but I guess I will leave as is for now until I know a bit more about React, but there will be a time and it will be very useful indeed!

**Comment by JacobMGEvans** [comment]
No problem, definitely review it and if you want to take whatever you like from it and use elsewhere instead of merging or just a reference. Have fun with it :+1:  best way to learn is try and break things and fix them lol

**Comment by shan5742** [comment]
Yeah I will definitely play around and your latter suggestion will probably be better as I started this a while back and have a few different ideas now

**Pull request merged**
